services:
  nginx:
    image: nginx:latest
    container_name: nginx-observability
    expose:
      - 80
    volumes:
      - ./observability.conf:/etc/nginx/conf.d/observability.conf
    labels:
      - proyect=observability
      - environment=prod
      - services=nginx
      - name=nginx-observability
    depends_on:
      - grafana
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    #expose:
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    labels:
      - proyect=observability
      - environment=prod
      - services=frontend
      - name=grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    labels:
      - proyect=observability
      - environment=prod
      - services=databases
      - name=loki
    expose:
      - 3100
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    labels:
      - proyect=observability
      - environment=prod
      - services=agent
      - name=promtail
    depends_on:
      - loki
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
